services:
  app:
    build:
      context: .
      args:
        IMAGE: ghcr.io/nationalarchives/tna-python-dev
        IMAGE_TAG: preview
    environment:
      - ENVIRONMENT_NAME=develop
      - CONFIG=config.Develop
      - DEBUG=true
      - SECRET_KEY=abc123
      - NPM_DEVELOP_COMMAND=dev
      - COOKIE_DOMAIN=localhost
      - CSP_STYLE_SRC='self',fonts.googleapis.com,p.typekit.net,use.typekit.net,'unsafe-inline'
      - CSP_FONT_SRC='self',fonts.gstatic.com,use.typekit.net
      - SESSION_REDIS_URL=redis://redis:6379/0
      - RATELIMIT_REDIS_URL=redis://redis:6379/1
      - ALTCHA_HMAC_KEY=abc123
      - CACHE_TYPE=RedisCache
      - CACHE_REDIS_URL=redis://redis:6379/2
      - SESSION_COOKIE_SECURE=False
    ports:
      - 65514:8080
    volumes:
      - ./:/app
    depends_on:
      - redis
    healthcheck:
      start_period: 10s
      start_interval: 2s

  redis:
    image: redis:latest

  docs:
    image: squidfunk/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 65513:8000
